name: build_countingbook_app

on: [ push ]

jobs:
    build_app:
        runs-on: ubuntu-latest
        steps:
            - id: s01
              run: echo "Building countingbook app, github ${{ github.ref_name }}"