name: build_countingbook_app

on: [ push ]

jobs:
    build_app:
        runs-on: ubuntu-latest
        steps:
            - id: s01
              run: echo "Building countingbook app, github ${{ github.ref_name }}"
            # setup the environment
            - run: echo "before " && ls -l

            - id: s02
              # set up the node environment with v24
              uses: actions/setup-node@v4
              with: 
                node-version: '24'
            - id: s03
              # check out repo's code into the runner
              uses: actions/checkout@v5
            - run: echo "after " && ls -l
            - id: s04
              # prepare the environment by installing the required packages
              run: npm i -g @angular/cli && npm ci && echo "Installed"
            - id: s05
              # build the app
              run: ng build
            - id: s06
              run: ls -l dist/countingbook/browser/
            - id: s07
              uses: nwtgck/actions-netlify@v3.0
              with:
                publish-dir: dist/countingbook/browser
                production-deploy: true
              env:
                NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}


